version: "3.9"
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: nikhil
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
