[env]
MISE_ENV_FILE = ".env"
LOGLEVEL = "info"
GIT_AUTHOR_EMAIL = "nikhil@theori.io"

[settings.python]
uv_venv_auto = true

[tools]
uv = "latest"
go = "latest"
node = "22"
terraform = "1"
tflint = "latest"
bun = "latest"
pnpm = "latest"
"npm:@openai/codex" = "latest"
"aqua:anthropics/claude-code" = "latest"

gh = "latest"
"go:oss.terrastruct.com/d2" = "latest"
"pipx:nickstenning/honcho" = "latest"
