#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# Copy into system keyboard on linux
# apt install xclip
# echo -n test | xclip
alias xclip="xclip -selection c"

alias be="bundle exec"

alias gitup="git checkout master && git fetch upstream && git rebase upstream/master"

alias workspace="docker run -ti --network host -v $HOME/.ssh:/root/.ssh debian:10 /bin/bash"

export TERM=xterm-256color

export PATH=$PATH:$HOME/tools/bin

# Terminal history fuzzy search
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# ASDF Version Manager
[ -f $HOME/.asdf/asdf.sh ] && . $HOME/.asdf/asdf.sh

# Starship Prompt (should be last thing in file?)
eval "$(starship init zsh)"
